### ISSUE TITLE
Support Native RowToColumnar

### ISSUE THREAD

**Issue by zzcclp** [Kyligence/ClickHouse#107]
> (you don't have to strictly follow this form)

**Support Native RowToColumnar**

supported row based RDD -> columnar RDD
this can be useful for test cases where the dataframe is constructed by  Seq(...).toDF, which is a row based RDD

**Describe the solution you'd like**

for a input InternalRow, we first convert it to a unsafeRow, and invoke native code to append it to CH block
the CH block can then be used as a ColumnarBatch in spark code.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by binmahone** [comment]
the function is mainly test by GlutenClickHouseSyntheticDataSuite: test("test all data types all agg")
