### ISSUE TITLE
Support some normal types e.g. "float"/"byte"/"short"/"decimal"

### ISSUE THREAD

**Issue by zzcclp** [Kyligence/ClickHouse#123]
> (you don't have to strictly follow this form)

Support some normal types e.g. "float"/"byte"/"short"/"decimal".

- [x] #71 

> A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by zhanglistar** [comment]
https://github.com/Kyligence/ClickHouse/pull/128
