### ISSUE TITLE
Create a docker image for Gluten + ClickHouse backend

### ISSUE THREAD

**Issue by zzcclp** [Kyligence/ClickHouse#15]
> (you don't have to strictly follow this form)

**Use case**

> A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by liuneng1994** [comment]
done
