### ISSUE TITLE
Core dump after stop Gluten

### ISSUE THREAD

**Issue by zzcclp** [Kyligence/ClickHouse#16]
> You have to provide the following information whenever possible.

Execute Q1 or  Q6 20 times, and stop Spark App, it will throw core dump error:
```
Stack: [0x00007fdb23024000,0x00007fdb23124000],  sp=0x00007fdb23122a60,  free space=1018k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libch.so+0x139be233]  DB::CHJIT::deleteCompiledModule(DB::CHJIT::CompiledModule const&)+0x53

VM_Operation (0x00007fd97d3f8740): Exit, mode: safepoint, requested by thread 0x00007fdb10003000

```

> A clear and concise description of what works not as it is supposed to.

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by liuneng1994** [comment]
fixed
