### ISSUE TITLE
Support CH NULLABLE

### ISSUE THREAD

**Issue by zzcclp** [Kyligence/ClickHouse#43]
> (you don't have to strictly follow this form)

Support CH NULLABLE, and fix issues.

1. NativeColumnarToRow 报错:
C  [[libch.so](http://libch.so/)+0x1252a0a0]  DB::ColumnVector<double>::getFloat64(unsigned long) const+0x0
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
io.glutenproject.vectorized.BlockNativeConverter.converColumarToRow(J)Lio/glutenproject/row/SparkRowInfo;+0

2. Shuffle nullable 字段不匹配

主要原因：
1. 聚合函数的partial result有单独的类型AggregateFunction
2. subtrait plan里的nullable属性有误，没有从表达式中获取实际结果

- [x] [Gluten-324](https://github.com/oap-project/gluten/issues/324)
- [x] #52 
- [x] #56 

> A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by liuneng1994** [comment]
https://spark.apache.org/docs/3.0.0-preview/sql-ref-null-semantics.html

**Comment by liuneng1994** [comment]
解决方案：
1. 表示AggregateFunction中间结果类型
通过给列名增加后缀，例如sum#123 变为sum#123#Partial#sum
名称第三个部分表示列为聚合的中间结果
名称第四个部分表示聚合函数
2. spark的聚合函数有很多的返回类型都是nullable的。clickhouse则会根据参数是否为nullable决定结果是否为nullable。
通过在聚合之前将输出为nullable的参数列转换为nullable解决
