### ISSUE TITLE
Support Select count(*) / count(1)  for ClickHouse backend

### ISSUE THREAD

**Issue by zzcclp** [Kyligence/ClickHouse#45]
> (you don't have to strictly follow this form)

执行 Select count(*) / count(1) from table 时，因为 Spark 并不会有 base schema 信息，CH 这端会报错：
Columns is empty: While executing ParquetBlockInputFormat: While executing BatchParquetFileSource

如果带有字段的查询，则没有问题：
Select count(*) / count(1) from table where a = 1。

> A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by zhanglistar** [comment]
Need add a cheapest column when column is empty.
