### ISSUE TITLE
Review OPPRO-214 and upgrade substrait.

### ISSUE THREAD

**Issue by zzcclp** [Kyligence/ClickHouse#55]
> (you don't have to strictly follow this form)

Review PR: [OPPRO-214](https://github.com/oap-project/gluten/pull/294), and upgrade substrait.

> A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by liuneng1994** [comment]
https://github.com/Kyligence/ClickHouse/pull/59
