### ISSUE TITLE
Support decimal type

### ISSUE THREAD

**Issue by zzcclp** [Kyligence/ClickHouse#71]
> (you don't have to strictly follow this form)

Support decimal type.

In TPCDS sql, there is cast(xxx as decimal).

> A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by zhanglistar** [comment]
https://github.com/Kyligence/ClickHouse/pull/128

**Comment by baibaichen** [comment]
duplicated with https://github.com/Kyligence/ClickHouse/issues/123
