### ISSUE TITLE
Support Concat expression

### ISSUE THREAD

**Issue by zzcclp** [Kyligence/ClickHouse#73]
> (you don't have to strictly follow this form)

Support Concat expression

> A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by taiyang-li** [comment]
implemented in https://github.com/Kyligence/ClickHouse/pull/172

**Comment by zzcclp** [comment]
thanks @taiyang-li
