### ISSUE TITLE
Add more UT for Gluten

### ISSUE THREAD

**Issue by zzcclp** [Kyligence/ClickHouse#84]
> (you don't have to strictly follow this form)

Add more UT for Gluten:

- [ ] #85 
- [x] Add a gluten-ut module for migrating some spark test cases.

> A clear and concise description of what is the intended usage scenario is.

**Describe the solution you'd like**

> A clear and concise description of what you want to happen.

**Describe alternatives you've considered**

> A clear and concise description of any alternative solutions or features you've considered.

**Additional context**

> Add any other context or screenshots about the feature request here.

**Comment by baibaichen** [comment]
please add concrete tasks

**Comment by zzcclp** [comment]
Spark SQL 的 UT 中，catalyst 和 SQL core 中的 UT 大概 9000 个左右；

Spark UT 大致分类：
1. 文臣提到的 expression 单测，在 sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions 目录下，这类是对所有 expression 的一个测试，主要是通过 **ExpressionEvalHelper** 来执行 expression 并验证结果，这里有很多 function，如果 Gluten 集成，需要修改这里的 function；

2.

**Comment by zzcclp** [comment]
迁移到 [Gluten-374](https://github.com/oap-project/gluten/issues/374) 进行跟踪。

**Comment by zzcclp** [comment]
Spark UT 详细列表及分工见 [Gluten-374](https://github.com/oap-project/gluten/issues/374)
