### ISSUE TITLE
some bugs when testing different aggregators on different types

### ISSUE THREAD

**Issue by binmahone** [Kyligence/ClickHouse#97]
> You have to provide the following information whenever possible.

**Describe what's wrong**

When I added a test to test different aggregators on different types (GlutenClickHouseSyntheticDataSuite on branch: binmahone/test_null_values , this test was originally supposed to cover [CH-87](https://github.com/Kyligence/ClickHouse/issues/87)). I found:

- [ ] some normal types are not supported to aggregate, e.g. "float"/"byte"/short"/"string", trace in #123 .
- [x] avg(int) and avg(bigint) can result wrong result (return NaN when input has two rows: Int.Max and Int.Min): fixed in [Gluten-343](https://github.com/oap-project/gluten/pull/345)
- [x] something went wrong when input has null values: fixed in #99 

The first one is not very urgent, but the second and third seems to be fatal.

**Does it reproduce on recent release?**

[The list of releases](https://github.com/ClickHouse/ClickHouse/blob/master/utils/list-versions/version_date.tsv)

**Enable crash reporting**

> If possible, change "enabled" to true in "send_crash_reports" section in `config.xml`:

```
<send_crash_reports>
        <!-- Changing <enabled> to true allows sending crash reports to -->
        <!-- the ClickHouse core developers team via Sentry https://sentry.io -->
        <enabled>false</enabled>
```

**How to reproduce**

* Which ClickHouse server version to use
* Which interface to use, if matters
* Non-default settings, if any
* `CREATE TABLE` statements for all tables involved
* Sample data for all these tables, use [clickhouse-obfuscator](https://github.com/ClickHouse/ClickHouse/blob/master/programs/obfuscator/Obfuscator.cpp#L42-L80) if necessary
* Queries to run that lead to unexpected result

**Expected behavior**

> A clear and concise description of what you expected to happen.

**Error message and/or stacktrace**

> If applicable, add screenshots to help explain your problem.

**Additional context**

> Add any other context about the problem here.

**Comment by liuneng1994** [comment]
avg(bigint) avg(int)结果不正确是因为在聚合的merge阶段，subtrait plan没有正确的表示出CH的中间结果类型，以bigint为例，预期为AggregateFunction(avg, Nullable(Int64)),而实际是AggregateFunction(avg, Nullable(Float64))

**Comment by liuneng1994** [comment]
当boolean列存在null时，进行聚合计算报错
done https://github.com/Kyligence/ClickHouse/pull/99

**Comment by zzcclp** [comment]
Use #123 to trace task one, close this issue.
